### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by MarcoCostantini** [lurchmath/openmath-js#10]
in the page https://lurchmath.github.io/openmath-js/site/source-code/ there is twice the link to 
https://github.com/lurchmath/openmath-js/blob/master/openmath.litcoffee which is broken.

That broken link is also in https://lurchmath.github.io/openmath-js/site/work-done/

**Comment by nathancarter** [comment]
Yes, we've moved off the dependence on CoffeeScript and switched to plain JavaScript.  I just haven't updated the docs yet.  Thanks for the reminder!

**Comment by nathancarter** [comment]
Fixed this with a bunch of commits this morning.  Thanks!
