### ISSUE TITLE
outdated dependencies

### ISSUE THREAD

**Issue by MarcoCostantini** [lurchmath/openmath-js#5]
Thank you for openmath-js

openmath-js depends on coffee-script@1.8.0 and jasmine-node@3.0.0

But https://www.npmjs.com/package/coffee-script says:

> This package has been deprecated
> Author message:
> CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

and https://www.npmjs.com/package/jasmine-node says:

> This project is now in maintenance mode. It is recommended to use the `jasmine` or `jasmine-npm` package whenever possible.

Installing openmath-js produces therefore warning messages.

**Comment by nathancarter** [comment]
Removed both dependencies in commits this morning.  They had been unused for awhile and were just lingering.  Thanks for the pointer.
